name: QA CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11.x]
        node-version: [8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: prepare tests
        run: npx serverest -t 10000 &
      - name: build project
        run: mvn clean install -DskipUTs=true -DskipITs=true
      - name: exec contract tests
        run: mvn clean test-compile -Dit.test=AllContractIT verify -DskipUTs=true
      - name: exec integration tests
        run: mvn clean test-compile -Dit.test=AllIntegrationIT verify -DskipUTs=true